apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: appsec-naisjob-failed
  namespace: appsec
spec:
  groups:
    - name: appsec
      rules:
        - alert: Naisjob failed
          expr: kube_job_failed{namespace="appsec"} > 0
          for: 1m
          annotations:
            description: "Naisjob {{ $labels.job_name }} failed"
            action: "check the grafana logs for {{ $labels.job_name }} @ https://grafana.nav.cloud.nais.io/d/ce5pol7gb1yioc/logger"
            summary: |-
              Notifies if the latest run failed
          labels:
            namespace: appsec
            severity: warning