apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: appsec-vulnerability-stats
  namespace: appsec
spec:
  image: "{{ image }}"
  command:
    - "java"
    - "-cp"
    - "/app/lib/*"
    - "no.nav.security.MainKt"
    - "--fetch-vulnerabilities"
  schedule: "0 4 * * *"
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  envFrom:
    - secret: appsec-stats-config
  env:
    - name: KAFKA_TOPIC
      value: "appsec.tpt"
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READWRITE
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: console.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki