apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: appsec-vulnerability-stats
  namespace: appsec
spec:
  image: "{{ image }}"
  command:
    - "--fetch-vulnerabilities"
  schedule: "0 4 * * *"
  ttlSecondsAfterFinished: 300
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  envFrom:
    - secret: appsec-stats-config
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READWRITE
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: console.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki