name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@dbbdc275be76ac10734476cc723d82dfe7ec6eda # ratchet:gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # ratchet:actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # ratchet:gradle/actions/setup-gradle@v3
      - name: Build shadowjar & test
        run: ./gradlew shadowjar
      - uses: nais/docker-build-push@099f6e6d0b4fa8899d03aae7dd274f87d4ff0651 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: appsec
          push_image: true
          docker_context: kubernetes-stats/
          pull: true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # ratchet:gradle/actions/dependency-submission@v3
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        cluster: [ "dev-fss", "dev-gcp", "prod-fss", "prod-gcp" ]
    environment: ${{ matrix.cluster }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@049ad8a74e82894c1247f227e014c888462c94d6 # ratchet:nais/deploy/actions/deploy@v2
        env:
          RESOURCE: kubernetes-stats/.nais/nais.yaml,kubernetes-stats/.nais/alerts.yaml
          CLUSTER: ${{ matrix.cluster }}
          IMAGE: ${{ needs.build.outputs.image }}
